// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentDatabaseApp.Data;

#nullable disable

namespace Student_Database.Migrations
{
    [DbContext(typeof(StudentDBContext))]
    partial class StudentDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentDatabaseApp.Data.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StudentEmail")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("StudentPhone")
                        .HasColumnType("int");

                    b.Property<string>("StudentlastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DOB = new DateTime(2010, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentAddress = "India",
                            StudentEmail = "roohi.sharma@hotmail.com",
                            StudentName = "Roohi",
                            StudentPhone = 587123210,
                            StudentlastName = "Sharma"
                        },
                        new
                        {
                            Id = 2,
                            DOB = new DateTime(2008, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentAddress = "USA",
                            StudentEmail = "john_philip@yahoo.com",
                            StudentName = "John",
                            StudentPhone = 187121210,
                            StudentlastName = "Philip"
                        },
                        new
                        {
                            Id = 3,
                            DOB = new DateTime(2005, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentAddress = "Africa",
                            StudentEmail = "Maria@gmail.com",
                            StudentName = "Maria",
                            StudentPhone = 102251110,
                            StudentlastName = "Wiliam"
                        },
                        new
                        {
                            Id = 4,
                            DOB = new DateTime(2007, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentAddress = "UK",
                            StudentEmail = "jeck@gmail.com",
                            StudentName = "Jeck",
                            StudentPhone = 447122274,
                            StudentlastName = "Gurge"
                        },
                        new
                        {
                            Id = 5,
                            DOB = new DateTime(2002, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentAddress = "UAE",
                            StudentEmail = "Almakhtum@gmail.com",
                            StudentName = "Al Makhtum",
                            StudentPhone = 998422274,
                            StudentlastName = "Haider"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
